NDefines_Graphics.NGraphics.VICTORY_POINTS_DISTANCE_CUTOFF = {450, 500, 1000}
NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF = {250, 350, 900}

NDefines_Graphics.NGraphics.COUNTRY_COLOR_HUE_MODIFIER = 0.0
NDefines_Graphics.NGraphics.COUNTRY_COLOR_SATURATION_MODIFIER = 1.0
NDefines_Graphics.NGraphics.COUNTRY_COLOR_BRIGHTNESS_MODIFIER = 0.75
NDefines_Graphics.NGraphics.GRADIENT_BORDERS_THICKNESS_COUNTRY_LOW = 1.0
NDefines_Graphics.NGraphics.GRADIENT_BORDERS_THICKNESS_COUNTRY_HIGH = 5.0

NDefines_Graphics.NGraphics.PROVINCE_BORDER_FADE_NEAR = 350
NDefines_Graphics.NGraphics.PROVINCE_BORDER_FADE_FAR = 355